/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BooksRouteImport } from './routes/books'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CopyrightRouteImport } from './routes/copyright'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as NewReleasesRouteImport } from './routes/new-releases'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as CheckoutBookIdRouteImport } from './routes/checkout.$bookId'
import { Route as PreviewBookIdRouteImport } from './routes/preview.$bookId'
import { Route as SuccessBookIdRouteImport } from './routes/success.$bookId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const NewReleasesRoute = NewReleasesRouteImport.update({
  id: '/new-releases',
  path: '/new-releases',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => BooksRoute,
} as any)
const CheckoutBookIdRoute = CheckoutBookIdRouteImport.update({
  id: '/checkout/$bookId',
  path: '/checkout/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewBookIdRoute = PreviewBookIdRouteImport.update({
  id: '/preview/$bookId',
  path: '/preview/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessBookIdRoute = SuccessBookIdRouteImport.update({
  id: '/success/$bookId',
  path: '/success/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/copyright': typeof CopyrightRoute
  '/library': typeof LibraryRoute
  '/new-releases': typeof NewReleasesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/checkout/$bookId': typeof CheckoutBookIdRoute
  '/preview/$bookId': typeof PreviewBookIdRoute
  '/success/$bookId': typeof SuccessBookIdRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/copyright': typeof CopyrightRoute
  '/library': typeof LibraryRoute
  '/new-releases': typeof NewReleasesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/checkout/$bookId': typeof CheckoutBookIdRoute
  '/preview/$bookId': typeof PreviewBookIdRoute
  '/success/$bookId': typeof SuccessBookIdRoute
  '/books': typeof BooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/copyright': typeof CopyrightRoute
  '/library': typeof LibraryRoute
  '/new-releases': typeof NewReleasesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/checkout/$bookId': typeof CheckoutBookIdRoute
  '/preview/$bookId': typeof PreviewBookIdRoute
  '/success/$bookId': typeof SuccessBookIdRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/books'
    | '/categories'
    | '/contact'
    | '/copyright'
    | '/library'
    | '/new-releases'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/books/$bookId'
    | '/checkout/$bookId'
    | '/preview/$bookId'
    | '/success/$bookId'
    | '/books/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/categories'
    | '/contact'
    | '/copyright'
    | '/library'
    | '/new-releases'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/books/$bookId'
    | '/checkout/$bookId'
    | '/preview/$bookId'
    | '/success/$bookId'
    | '/books'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/books'
    | '/categories'
    | '/contact'
    | '/copyright'
    | '/library'
    | '/new-releases'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/books/$bookId'
    | '/checkout/$bookId'
    | '/preview/$bookId'
    | '/success/$bookId'
    | '/books/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BooksRoute: typeof BooksRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  CopyrightRoute: typeof CopyrightRoute
  LibraryRoute: typeof LibraryRoute
  NewReleasesRoute: typeof NewReleasesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  TermsRoute: typeof TermsRoute
  CheckoutBookIdRoute: typeof CheckoutBookIdRoute
  PreviewBookIdRoute: typeof PreviewBookIdRoute
  SuccessBookIdRoute: typeof SuccessBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-releases': {
      id: '/new-releases'
      path: '/new-releases'
      fullPath: '/new-releases'
      preLoaderRoute: typeof NewReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof BooksRoute
    }
    '/checkout/$bookId': {
      id: '/checkout/$bookId'
      path: '/checkout/$bookId'
      fullPath: '/checkout/$bookId'
      preLoaderRoute: typeof CheckoutBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$bookId': {
      id: '/preview/$bookId'
      path: '/preview/$bookId'
      fullPath: '/preview/$bookId'
      preLoaderRoute: typeof PreviewBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success/$bookId': {
      id: '/success/$bookId'
      path: '/success/$bookId'
      fullPath: '/success/$bookId'
      preLoaderRoute: typeof SuccessBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BooksRouteChildren {
  BooksBookIdRoute: typeof BooksBookIdRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksBookIdRoute: BooksBookIdRoute,
  BooksIndexRoute: BooksIndexRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BooksRoute: BooksRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  CopyrightRoute: CopyrightRoute,
  LibraryRoute: LibraryRoute,
  NewReleasesRoute: NewReleasesRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  TermsRoute: TermsRoute,
  CheckoutBookIdRoute: CheckoutBookIdRoute,
  PreviewBookIdRoute: PreviewBookIdRoute,
  SuccessBookIdRoute: SuccessBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
